"""initial schema

Revision ID: 4e8a81203a0e
Revises: 
Create Date: 2026-08-30 04:53:18.140658

"""
from typing import Sequence, Union

from alembic import op

from app.core.config import get_settings

EMBEDDING_DIM = get_settings().embedding_dimensions
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e8a81203a0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extensions first. The compose init script also creates these, but a
    # database provisioned any other way must still migrate cleanly.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.Enum('OFFICIAL_GOVERNMENT', 'OFFICIAL_COMPANY', 'PRIMARY_DOCUMENT', 'SCIENTIFIC_SOURCE', 'NEWS_AGENCY', 'NEWS_ORGANIZATION', 'SPECIALIST_PUBLICATION', 'BLOG', 'SOCIAL_MEDIA', 'USER_PROVIDED', 'UNKNOWN', name='sourcetype', native_enum=False, length=40), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('primary_source_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_satirical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index(op.f('ix_sources_created_at'), 'sources', ['created_at'], unique=False)
    op.create_index(op.f('ix_sources_domain'), 'sources', ['domain'], unique=True)
    op.create_table('submissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('content_type', sa.Enum('TEXT', 'ARTICLE_URL', 'SOCIAL_URL', 'IMAGE', 'SCREENSHOT', 'IMAGE_WITH_CAPTION', 'VIDEO', 'VIDEO_WITH_CAPTION', name='submissiontype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSING', 'COMPLETED', 'REJECTED', 'FAILED', name='submissionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('submitted_url', sa.String(length=2048), nullable=True),
    sa.Column('canonical_url', sa.String(length=2048), nullable=True),
    sa.Column('detected_language', sa.String(length=16), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('intake_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions'))
    )
    op.create_index(op.f('ix_submissions_content_hash'), 'submissions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_submissions_created_at'), 'submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_submissions_detected_language'), 'submissions', ['detected_language'], unique=False)
    op.create_index(op.f('ix_submissions_public_id'), 'submissions', ['public_id'], unique=True)
    op.create_index('ix_submissions_recent', 'submissions', ['created_at', 'status'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('IMAGE', 'SCREENSHOT', 'VIDEO', name='mediakind', native_enum=False, length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('storage_bucket', sa.String(length=128), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('perceptual_hash', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('technical_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_media_assets_submission_id_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets'))
    )
    op.create_index(op.f('ix_media_assets_created_at'), 'media_assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_assets_perceptual_hash'), 'media_assets', ['perceptual_hash'], unique=False)
    op.create_index(op.f('ix_media_assets_public_id'), 'media_assets', ['public_id'], unique=True)
    op.create_index(op.f('ix_media_assets_sha256'), 'media_assets', ['sha256'], unique=False)
    op.create_index(op.f('ix_media_assets_submission_id'), 'media_assets', ['submission_id'], unique=False)
    op.create_table('retrieved_documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('simhash', sa.String(length=32), nullable=True),
    sa.Column('retrieval_provider', sa.Enum('INDEXED_CORPUS', 'GDELT', 'RSS_CORPUS', 'DIRECT_URL', 'OFFICIAL_SOURCE', name='retrievalprovidername', native_enum=False, length=32), nullable=True),
    sa.Column('fetch_status', sa.String(length=32), nullable=True),
    sa.Column('fetch_error', sa.String(length=255), nullable=True),
    sa.Column('injection_detected', sa.Boolean(), nullable=False),
    sa.Column('injection_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_retrieved_documents_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieved_documents'))
    )
    op.create_index('ix_documents_dedup', 'retrieved_documents', ['content_hash', 'canonical_url'], unique=False)
    op.create_index('ix_documents_published', 'retrieved_documents', ['published_at', 'source_id'], unique=False)
    op.create_index(op.f('ix_retrieved_documents_canonical_url'), 'retrieved_documents', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_retrieved_documents_content_hash'), 'retrieved_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_retrieved_documents_created_at'), 'retrieved_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_retrieved_documents_language'), 'retrieved_documents', ['language'], unique=False)
    op.create_index(op.f('ix_retrieved_documents_published_at'), 'retrieved_documents', ['published_at'], unique=False)
    op.create_index(op.f('ix_retrieved_documents_simhash'), 'retrieved_documents', ['simhash'], unique=False)
    op.create_index(op.f('ix_retrieved_documents_source_id'), 'retrieved_documents', ['source_id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='verificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('current_stage', sa.Enum('QUEUED', 'NORMALIZING', 'EXTRACTING_CONTENT', 'DETECTING_LANGUAGE', 'EXTRACTING_CLAIMS', 'GENERATING_QUERIES', 'RETRIEVING_EVIDENCE', 'FETCHING_DOCUMENTS', 'EXTRACTING_EVIDENCE', 'CLASSIFYING_EVIDENCE', 'ANALYZING_MEDIA', 'SCORING', 'GENERATING_REPORT', 'COMPLETED', 'FAILED', name='pipelinestage', native_enum=False, length=40), nullable=False),
    sa.Column('overall_verdict', sa.Enum('VERIFIED', 'LIKELY_TRUE', 'PARTLY_TRUE', 'MISLEADING', 'UNVERIFIED', 'LIKELY_FALSE', 'FALSE', 'SATIRE', 'OPINION', name='verdict', native_enum=False, length=32), nullable=True),
    sa.Column('confidence_band', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidenceband', native_enum=False, length=16), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('degradation_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('scoring_version', sa.String(length=32), nullable=False),
    sa.Column('retrieval_version', sa.String(length=32), nullable=False),
    sa.Column('provider_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_verifications_submission_id_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verifications'))
    )
    op.create_index(op.f('ix_verifications_created_at'), 'verifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_verifications_overall_verdict'), 'verifications', ['overall_verdict'], unique=False)
    op.create_index(op.f('ix_verifications_public_id'), 'verifications', ['public_id'], unique=True)
    op.create_index('ix_verifications_recent', 'verifications', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_verifications_status'), 'verifications', ['status'], unique=False)
    op.create_index(op.f('ix_verifications_submission_id'), 'verifications', ['submission_id'], unique=False)
    op.create_index('ix_verifications_verdict_recent', 'verifications', ['overall_verdict', 'created_at'], unique=False)
    op.create_table('article_index',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('searchable_text', sa.Text(), nullable=False),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['retrieved_documents.id'], name=op.f('fk_article_index_document_id_retrieved_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_index'))
    )
    op.create_index(op.f('ix_article_index_created_at'), 'article_index', ['created_at'], unique=False)
    op.create_index(op.f('ix_article_index_document_id'), 'article_index', ['document_id'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('verification_id', sa.BigInteger(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('normalized_claim', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('predicate', sa.String(length=500), nullable=True),
    sa.Column('object', sa.String(length=500), nullable=True),
    sa.Column('claim_type', sa.Enum('EVENT', 'STATISTIC', 'QUOTE', 'ATTRIBUTION', 'CAUSAL', 'EXISTENCE', 'IDENTITY', 'LOCATION', 'TEMPORAL', 'PREDICTION', 'OPINION', 'OTHER', name='claimtype', native_enum=False, length=32), nullable=False),
    sa.Column('origin', sa.Enum('USER_TEXT', 'USER_CAPTION', 'ARTICLE_TEXT', 'SOCIAL_POST_TEXT', 'VIDEO_TRANSCRIPT', 'ON_SCREEN_TEXT', 'OCR_TEXT', name='claimorigin', native_enum=False, length=32), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('money', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('percentages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verdict', sa.Enum('VERIFIED', 'LIKELY_TRUE', 'PARTLY_TRUE', 'MISLEADING', 'UNVERIFIED', 'LIKELY_FALSE', 'FALSE', 'SATIRE', 'OPINION', name='verdict', native_enum=False, length=32), nullable=True),
    sa.Column('confidence_band', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidenceband', native_enum=False, length=16), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], name=op.f('fk_claims_verification_id_verifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_index(op.f('ix_claims_created_at'), 'claims', ['created_at'], unique=False)
    op.create_index(op.f('ix_claims_verdict'), 'claims', ['verdict'], unique=False)
    op.create_index(op.f('ix_claims_verification_id'), 'claims', ['verification_id'], unique=False)
    op.create_index('ix_claims_verification_sequence', 'claims', ['verification_id', 'sequence'], unique=False)
    op.create_table('evidence_clusters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('verification_id', sa.BigInteger(), nullable=False),
    sa.Column('representative_document_id', sa.BigInteger(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('clustering_method', sa.String(length=32), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['representative_document_id'], ['retrieved_documents.id'], name=op.f('fk_evidence_clusters_representative_document_id_retrieved_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], name=op.f('fk_evidence_clusters_verification_id_verifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_clusters'))
    )
    op.create_index(op.f('ix_evidence_clusters_created_at'), 'evidence_clusters', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_clusters_verification_id'), 'evidence_clusters', ['verification_id'], unique=False)
    op.create_table('media_analyses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('verification_id', sa.BigInteger(), nullable=False),
    sa.Column('media_asset_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('IMAGE', 'SCREENSHOT', 'VIDEO', name='mediakind', native_enum=False, length=32), nullable=False),
    sa.Column('metadata_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('manipulation_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('corpus_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('earliest_known_appearance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predates_claimed_event', sa.Boolean(), nullable=True),
    sa.Column('ocr_status', sa.Enum('COMPLETED', 'UNAVAILABLE', 'FAILED', 'SKIPPED', name='analysisavailability', native_enum=False, length=32), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_engine', sa.String(length=64), nullable=True),
    sa.Column('ocr_unavailable_reason', sa.String(length=255), nullable=True),
    sa.Column('screenshot_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keyframe_count', sa.Integer(), nullable=True),
    sa.Column('keyframes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scene_change_count', sa.Integer(), nullable=True),
    sa.Column('analysis_availability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('fk_media_analyses_media_asset_id_media_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], name=op.f('fk_media_analyses_verification_id_verifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_analyses'))
    )
    op.create_index(op.f('ix_media_analyses_created_at'), 'media_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_analyses_media_asset_id'), 'media_analyses', ['media_asset_id'], unique=False)
    op.create_index(op.f('ix_media_analyses_verification_id'), 'media_analyses', ['verification_id'], unique=False)
    op.create_table('verification_revisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('verification_id', sa.BigInteger(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Enum('VERIFIED', 'LIKELY_TRUE', 'PARTLY_TRUE', 'MISLEADING', 'UNVERIFIED', 'LIKELY_FALSE', 'FALSE', 'SATIRE', 'OPINION', name='verdict', native_enum=False, length=32), nullable=True),
    sa.Column('confidence_band', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidenceband', native_enum=False, length=16), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('scoring_version', sa.String(length=32), nullable=False),
    sa.Column('retrieval_version', sa.String(length=32), nullable=False),
    sa.Column('provider_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trigger', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], name=op.f('fk_verification_revisions_verification_id_verifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_revisions'))
    )
    op.create_index(op.f('ix_verification_revisions_created_at'), 'verification_revisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_verification_revisions_verification_id'), 'verification_revisions', ['verification_id'], unique=False)
    op.create_index('uq_revision_number', 'verification_revisions', ['verification_id', 'revision_number'], unique=True)
    op.create_table('verification_stages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('verification_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.Enum('QUEUED', 'NORMALIZING', 'EXTRACTING_CONTENT', 'DETECTING_LANGUAGE', 'EXTRACTING_CLAIMS', 'GENERATING_QUERIES', 'RETRIEVING_EVIDENCE', 'FETCHING_DOCUMENTS', 'EXTRACTING_EVIDENCE', 'CLASSIFYING_EVIDENCE', 'ANALYZING_MEDIA', 'SCORING', 'GENERATING_REPORT', 'COMPLETED', 'FAILED', name='pipelinestage', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'SKIPPED', 'DEGRADED', 'FAILED', name='stagestatus', native_enum=False, length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stage_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], name=op.f('fk_verification_stages_verification_id_verifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_stages'))
    )
    op.create_index(op.f('ix_verification_stages_verification_id'), 'verification_stages', ['verification_id'], unique=False)
    op.create_index('uq_verification_stage', 'verification_stages', ['verification_id', 'stage'], unique=True)
    op.create_table('video_transcripts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('media_asset_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'UNAVAILABLE', 'FAILED', 'SKIPPED', name='analysisavailability', native_enum=False, length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('language_confidence', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('duration_processed_seconds', sa.Float(), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('unavailable_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('fk_video_transcripts_media_asset_id_media_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_transcripts'))
    )
    op.create_index(op.f('ix_video_transcripts_created_at'), 'video_transcripts', ['created_at'], unique=False)
    op.create_index(op.f('ix_video_transcripts_media_asset_id'), 'video_transcripts', ['media_asset_id'], unique=True)
    op.create_table('claim_entities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('claim_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('normalized', sa.String(length=500), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_entities_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_entities'))
    )
    op.create_index(op.f('ix_claim_entities_claim_id'), 'claim_entities', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_entities_normalized'), 'claim_entities', ['normalized'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('claim_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('cluster_id', sa.BigInteger(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('relationship_type', sa.Enum('SUPPORTS', 'CONTRADICTS', 'NEUTRAL', 'INSUFFICIENT', name='evidencerelationship', native_enum=False, length=32), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('strength_score', sa.Float(), nullable=False),
    sa.Column('temporal_relevance', sa.Float(), nullable=True),
    sa.Column('directness', sa.Float(), nullable=True),
    sa.Column('source_factor', sa.Float(), nullable=True),
    sa.Column('computed_weight', sa.Float(), nullable=True),
    sa.Column('weight_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('classifier_name', sa.String(length=64), nullable=True),
    sa.Column('classifier_version', sa.String(length=32), nullable=True),
    sa.Column('classifier_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_evidence_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], ['evidence_clusters.id'], name=op.f('fk_evidence_cluster_id_evidence_clusters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['retrieved_documents.id'], name=op.f('fk_evidence_document_id_retrieved_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_evidence_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_claim_id'), 'evidence', ['claim_id'], unique=False)
    op.create_index('ix_evidence_claim_relationship', 'evidence', ['claim_id', 'relationship_type'], unique=False)
    op.create_index(op.f('ix_evidence_cluster_id'), 'evidence', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_evidence_created_at'), 'evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_document_id'), 'evidence', ['document_id'], unique=False)
    op.create_index(op.f('ix_evidence_relationship_type'), 'evidence', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_evidence_source_id'), 'evidence', ['source_id'], unique=False)
    op.create_table('retrieval_queries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('claim_id', sa.BigInteger(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.Enum('INDEXED_CORPUS', 'GDELT', 'RSS_CORPUS', 'DIRECT_URL', 'OFFICIAL_SOURCE', name='retrievalprovidername', native_enum=False, length=32), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_retrieval_queries_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_queries'))
    )
    op.create_index(op.f('ix_retrieval_queries_claim_id'), 'retrieval_queries', ['claim_id'], unique=False)
    op.create_index(op.f('ix_retrieval_queries_created_at'), 'retrieval_queries', ['created_at'], unique=False)
    # ### end Alembic commands ###



    # ---- Hybrid retrieval structures -------------------------------------
    # These cannot be autogenerated: the vector column type and the GIN/HNSW
    # indexes are pgvector- and PostgreSQL-specific. See docs/RETRIEVAL.md.

    # Semantic leg: embedding vector sized to the configured model.
    op.execute(
        f"ALTER TABLE article_index ADD COLUMN embedding vector({EMBEDDING_DIM})"
    )

    # Keyword leg: a generated tsvector column keeps the search index in sync
    # with the text automatically, so it can never drift out of date.
    op.execute(
        """
        ALTER TABLE article_index
        ADD COLUMN search_vector tsvector
        GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED
        """
    )
    op.execute(
        "CREATE INDEX ix_article_index_search_vector ON article_index USING GIN (search_vector)"
    )

    # HNSW over cosine distance: approximate nearest neighbour, which stays fast
    # as the corpus grows where an exact scan would not.
    op.execute(
        """
        CREATE INDEX ix_article_index_embedding_hnsw
        ON article_index USING hnsw (embedding vector_cosine_ops)
        """
    )

    # Trigram index for fuzzy title matching during near-duplicate detection.
    op.execute(
        "CREATE INDEX ix_documents_title_trgm ON retrieved_documents USING GIN (title gin_trgm_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_documents_title_trgm")
    op.execute("DROP INDEX IF EXISTS ix_article_index_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS ix_article_index_search_vector")

    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieval_queries_created_at'), table_name='retrieval_queries')
    op.drop_index(op.f('ix_retrieval_queries_claim_id'), table_name='retrieval_queries')
    op.drop_table('retrieval_queries')
    op.drop_index(op.f('ix_evidence_source_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_relationship_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_document_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_created_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_cluster_id'), table_name='evidence')
    op.drop_index('ix_evidence_claim_relationship', table_name='evidence')
    op.drop_index(op.f('ix_evidence_claim_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_claim_entities_normalized'), table_name='claim_entities')
    op.drop_index(op.f('ix_claim_entities_claim_id'), table_name='claim_entities')
    op.drop_table('claim_entities')
    op.drop_index(op.f('ix_video_transcripts_media_asset_id'), table_name='video_transcripts')
    op.drop_index(op.f('ix_video_transcripts_created_at'), table_name='video_transcripts')
    op.drop_table('video_transcripts')
    op.drop_index('uq_verification_stage', table_name='verification_stages')
    op.drop_index(op.f('ix_verification_stages_verification_id'), table_name='verification_stages')
    op.drop_table('verification_stages')
    op.drop_index('uq_revision_number', table_name='verification_revisions')
    op.drop_index(op.f('ix_verification_revisions_verification_id'), table_name='verification_revisions')
    op.drop_index(op.f('ix_verification_revisions_created_at'), table_name='verification_revisions')
    op.drop_table('verification_revisions')
    op.drop_index(op.f('ix_media_analyses_verification_id'), table_name='media_analyses')
    op.drop_index(op.f('ix_media_analyses_media_asset_id'), table_name='media_analyses')
    op.drop_index(op.f('ix_media_analyses_created_at'), table_name='media_analyses')
    op.drop_table('media_analyses')
    op.drop_index(op.f('ix_evidence_clusters_verification_id'), table_name='evidence_clusters')
    op.drop_index(op.f('ix_evidence_clusters_created_at'), table_name='evidence_clusters')
    op.drop_table('evidence_clusters')
    op.drop_index('ix_claims_verification_sequence', table_name='claims')
    op.drop_index(op.f('ix_claims_verification_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_verdict'), table_name='claims')
    op.drop_index(op.f('ix_claims_created_at'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_article_index_document_id'), table_name='article_index')
    op.drop_index(op.f('ix_article_index_created_at'), table_name='article_index')
    op.drop_table('article_index')
    op.drop_index('ix_verifications_verdict_recent', table_name='verifications')
    op.drop_index(op.f('ix_verifications_submission_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_status'), table_name='verifications')
    op.drop_index('ix_verifications_recent', table_name='verifications')
    op.drop_index(op.f('ix_verifications_public_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_overall_verdict'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_created_at'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_retrieved_documents_source_id'), table_name='retrieved_documents')
    op.drop_index(op.f('ix_retrieved_documents_simhash'), table_name='retrieved_documents')
    op.drop_index(op.f('ix_retrieved_documents_published_at'), table_name='retrieved_documents')
    op.drop_index(op.f('ix_retrieved_documents_language'), table_name='retrieved_documents')
    op.drop_index(op.f('ix_retrieved_documents_created_at'), table_name='retrieved_documents')
    op.drop_index(op.f('ix_retrieved_documents_content_hash'), table_name='retrieved_documents')
    op.drop_index(op.f('ix_retrieved_documents_canonical_url'), table_name='retrieved_documents')
    op.drop_index('ix_documents_published', table_name='retrieved_documents')
    op.drop_index('ix_documents_dedup', table_name='retrieved_documents')
    op.drop_table('retrieved_documents')
    op.drop_index(op.f('ix_media_assets_submission_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_sha256'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_public_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_perceptual_hash'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_created_at'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('ix_submissions_recent', table_name='submissions')
    op.drop_index(op.f('ix_submissions_public_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_detected_language'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_created_at'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_content_hash'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_sources_domain'), table_name='sources')
    op.drop_index(op.f('ix_sources_created_at'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
